---
title: "PROJEKT"
author: "Hubert Makowski"
date: "`r Sys.Date()`"
output: 
  html_document: 
    highlight: textmate
    keep_md: yes
    theme: yeti
    toc: yes
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Wczytywanie bibliotek
1,2

```{r load_packages, message=FALSE}
library(dplyr)
library(tidyr)
library(data.table)
library(knitr)
```

## Wczytywanie danych
3

```{r Read data}
lines <- data.table::fread('all_summary.csv', sep = ';')
#lines2 <- read.csv('all_summary.csv',skip=5000,nrows = 5000, sep = ';')
kable(lines, format = "latex", booktabs = TRUE)
```
## Filtrowanie res_name
4

```{r Delete res_name}
'%!in%' <- function(x,y)!('%in%'(x,y))

lines_filtered <- lines %>% filter(res_name %!in% c('UNK', 'UNX', 'UNL', 'DUM', 'N', 'BLOB', 'ALA', 'ARG', 'ASN', 'ASP', 'CYS', 'GLN', 'GLU', 'GLY', 'HIS', 'ILE', 'LEU', 'LYS', 'MET', 'MSE', 'PHE', 'PRO', 'SEC', 'SER', 'THR', 'TRP', 'TYR', 'VAL', 'DA', 'DG', 'DT', 'DC', 'DU', 'A', 'G', 'T', 'C', 'U', 'HOH', 'H20', 'WAT'))
```

##Kolumny z wartoœciami NA
5
```{r eval=FALSE}
nacols <- function(df) {
   colnames(df)[unlist(lapply(df, function(x) any(is.na(x))))]
}
nacols(lines_filtered) -> row_with_na_value
lines_filtered_with_na <- lines_filtered %>% select(row_with_na_value)
lines_filtered_with_na[which(is.na(.))]
lines_filtered_without_na <- lines_filtered %>% select(-row_with_na_value)

#omija wiersze z wartoœcia NA x <- na.omit(airquality)
part_and_ligand <- lines_filtered_with_na %>% select(res_name,starts_with('part_01')) %>% group_by(res_name)

```

##Zbiór i jego podstawowe statystyki
6
```{r Simple info}
dim(lines)
summary.data.frame(lines_filtered, median) -> lines_filtered_summary
kable(head(lines_filtered_summary))
#lines_filtered %>% summarise_all(funs(min, max, mean, sd,med = median),na.rm=TRUE)
#podstawowe statystyki
```

##Ograniczenie res_name do 50
7,9
```{r eval=FALSE}
lines %>% group_by(res_name) %>% summarise(ile=n()) %>% arrange(desc(ile)) -> res_name_top
res_name_top_50 <- head(res_name_top,50)
```

##Korelacje miêdzy zmiennymi
8

```{r corelation}

```

## PART_
12

```{r eval=FALSE}
parts_01 <- lines_filtered %>% select(starts_with('part_01'))
parts_01_with_mean <- parts_01 %>% summarise_all(mean,na.rm = TRUE)
#parts_01_with_mean_without_na <- parts_01_with_mean %>%select_if(function(x) !any(is.na(x)))
#parts_01_with_mean_with_na <- parts_01_with_mean %>%select_if(function(x) any(is.na(x)))
#wzi¹æ tem którema maj¹ wartoœæ,a te które nie maj¹ to pojedynczo wyci¹æ omit wiersze i wyliczyæ podsumowanie œredni¹
#parts_01 %>% filter
```


## Including Plots

```{r pressure, echo=FALSE,eval=FALSE}
f <- function(x, pos){
  #z ka¿dym chunkiem coœ ...
}
read_csv_chunked(readr_example("mtcars.csv"), DataFrameCallback$new(f), chunk_size = 5000, progress = show_progress())
```
